### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by Smattr** [blackk-foxx/apcsa#6]
Noob question, but am I supposed to create the JSON files manually? After installing the dependencies and merging @blackk-foxx's #2, I get the following when running:

```bash
$ python3 RunGoogleClassroom.py -xlsx hello.xlsx
/Users/matthew/Library/Python/3.6/lib/python/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "/Users/matthew/Library/Python/3.6/lib/python/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RunGoogleClassroom.py", line 246, in <module>
    main()
  File "RunGoogleClassroom.py", line 168, in main
    (service, drive) = Open_Classroom(args)
  File "RunGoogleClassroom.py", line 46, in Open_Classroom
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
  File "/Users/matthew/Library/Python/3.6/lib/python/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matthew/Library/Python/3.6/lib/python/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/Users/matthew/Library/Python/3.6/lib/python/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Users/matthew/Library/Python/3.6/lib/python/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'credentials.json', 'No such file or directory', 2)
```

**Comment by blackk-foxx** [comment]
Hi Matt,

If you followed the steps in the README file, you’ll have a credentials.json file in your download folder.  Move it into your python scripts directory, and you’re good to go.

Todd

**Comment by Smattr** [comment]
Ah, sorry, I somehow overlooked the first line!
